CREATE TABLE [dbo].[Stocks]
(
    [Id]         INT IDENTITY(1,1) NOT NULL,
    [Symbol]     NVARCHAR(50) NOT NULL,
    [Name]       NVARCHAR(255) NOT NULL,
    [Price]      DECIMAL(38, 10) NOT NULL,
    [CompanyId]  UNIQUEIDENTIFIER NOT NULL,
    [CreatedAt]  DATETIME2 NOT NULL,
    [UpdatedAt]  DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [LastUpdate] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME ([UpdatedAt], [LastUpdate]),
    CONSTRAINT [PK_Stocks] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [PK_Stocks_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Companies] ([Id]) ON DELETE CASCADE
)
    WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[StocksHistory]));
